name: Update Battery Prices

on:
  schedule:
    # Run every Sunday at 6:00 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Update all battery prices
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      run: node scripts/update-all-prices.js
      
    - name: Log completion
      run: echo "Battery price update completed at $(date)"
